### ISSUE TITLE
Upgrade static-metric dependencies

### ISSUE THREAD

**Issue by breeswish** [tikv/rust-prometheus#198]
syn, proc_macro2 and quote can be upgraded.

**Comment by hdost** [comment]
It looks like the `static-metric` it's all up to date since `acef86b8ab13912eb30c7bf4a5e027b2a9cc04dc`

**Comment by mxinden** [comment]
True. Thanks for the pointer @hdost. A `cargo upgrade` does not bump any major (for < `1.0` minor) versions. Given that `static-metric` is mentioned in the `workspace` section of the root `Cargo.toml` Dependabot should keep everything up to date.
