### ISSUE TITLE
Registry doesn't return AlreadyReg

### ISSUE THREAD

**Issue by jamessewell** [tikv/rust-prometheus#247]
Hi,

If I register a metric twice then I get a `prometheus::Error::Msg(m)` with the message:

```
... already exists with the same fully-qualified name and const label values
```

I would *expect* that I would just get `prometheus::Error::AlreadyReg` - which is a lot easier to catch than a freeform String error which appears to have multiple uses.

The issue seems to be here: 
https://github.com/pingcap/rust-prometheus/blob/4cbc0b6d948c0b73182574f370223e8241bb1811/src/registry.rs#L44-L50

Quoting out this section means that the error is caught correctly here:
https://github.com/pingcap/rust-prometheus/blob/4cbc0b6d948c0b73182574f370223e8241bb1811/src/registry.rs#L90

Cheers

**Comment by breeswish** [comment]
Thanks for the report! This behaviour indeed does not match the function's documentation. We will fix it.
