### ISSUE TITLE
Update dependency on spin crate

### ISSUE THREAD

**Issue by 64** [tikv/rust-prometheus#256]
There’s currently some issues with `spin`’s RwLock implementation which you seem to make use of (in the worst case leading to unsynchronised reads/writes). You should update to the new version when the fix lands. See https://github.com/mvdnes/spin-rs/issues/65

**Comment by breeswish** [comment]
Great thanks for the reminding! We will keep track of it.

**Comment by 64** [comment]
The fix has been merged now, published as `0.5.2`.

**Comment by breeswish** [comment]
Would you like to open a PR?

**Comment by bbigras** [comment]
This should be closed as already done https://github.com/tikv/rust-prometheus/pull/274
