### ISSUE TITLE
Cron builds

### ISSUE THREAD

**Issue by Hoverbear** [tikv/rust-prometheus#260]
**Is your feature request related to a problem? Please describe.**

Add daily or weekly cron jobs to detect breakage early, as per https://github.com/pingcap/rust-prometheus/issues/258#issuecomment-515888540

**Describe the solution you'd like**

I think weekly is enough.

**Describe alternatives you've considered**

I considered daily, but it seems like overkill.

**Additional context**

https://github.com/pingcap/rust-prometheus/issues/258#issuecomment-515888540

**Comment by Hoverbear** [comment]
What do you think @breeswish ?

**Comment by breeswish** [comment]
Maybe this can be done automatically by Travis CI?

**Comment by Hoverbear** [comment]
Yes! https://docs.travis-ci.com/user/cron-jobs/

**Comment by hdost** [comment]
Why not just run on merge?

**Comment by lucab** [comment]
> I think weekly is enough.

I just checked and this is indeed the current Travis setup (I'm not sure when/who changed it). Closing.

 > Why not just run on pr and merge?

Because stable+beta+nightly can drift into an undetected broken state, see https://github.com/tikv/rust-prometheus/issues/258.
