### ISSUE TITLE
Consider switching from procinfo to procfs

### ISSUE THREAD

**Issue by brndnmtthws** [tikv/rust-prometheus#272]
The procinfo crate seems somewhat inactive, and there's an alternative called [procfs](https://github.com/eminence/procfs) which appears more well maintained.

It would be great to be able to capture additional process metrics for observability.

Additionally, it would be nice to mix OS level metrics in with process metrics. For example, I want to know how the process is affecting CPU pressure on the host system.

**Comment by eminence** [comment]
I took a look at how `rust-prometheus` is using `procinfo`, and it looks to be straightforward to switch to `procfs`.   `process_collector.rs` has some code that'll parse `/proc/pid/limits`, and this is missing from procfs.  I'll enhance procfs to also parse process limits, and then open a PR that'll make the conversion from procinfo to procfs.

**Comment by brndnmtthws** [comment]
#290 addresses the main issue, however:

As a suggestion, before adding other metrics (like the pressure info I suggested), it might be worth collecting feedback to see what sort of metrics people would like to include.

Here are some of the things I'd like to see:

* CPU/mem/IO pressure
* IO stats from `/proc/[pid]/io`
* netstats: number of listeners, connections by proto, etc

**Comment by eminence** [comment]
Would it be worth adding these types of host-metrics as a new crate?   (Either as a short-term development project before merging into rust-prometheus, or as a new companion crate to rust-prometheus)

**Comment by breeswish** [comment]
@overvenus @brson @nrc How do you think about https://github.com/tikv/rust-prometheus/issues/272#issuecomment-546707185 and https://github.com/tikv/rust-prometheus/issues/272#issuecomment-546714574 ?

**Comment by nrc** [comment]
> it might be worth collecting feedback to see what sort of metrics people would like to include.

I think this is a good idea!

> Here are some of the things I'd like to see:

These all seem good to have. I'd want to check the overheads for collection and exactly what info we can offer.

> Would it be worth adding these types of host-metrics as a new crate? (Either as a short-term development project before merging into rust-prometheus, or as a new companion crate to rust-prometheus)

I think they should probably be an external metric which Prometheus can read, rather than part of this crate (but I admit I am not very familiar with the Prometheus architecture).
