### ISSUE TITLE
Consider separate generics for `label` and `value` in `const_label`

### ISSUE THREAD

**Issue by nagisa** [tikv/rust-prometheus#281]
Currently the `const_label` methods look like this (in a semi pseudo notation):

```rust
pub fn HistogramOpts::const_label<S: Into<String>>(self, name: S, value: S) -> Self;
pub fn Opts::const_label<S: Into<String>>(self, name: S, value: S) -> Self;
```

This signature is perfectly fine when both `name` and `value` are the same type, but in my experience they, more often than not, want to be different (e.g. `&'static str` for `name` and something else for `value`).

IMO these methods should be rewritten to:

```rust
pub fn HistogramOpts::const_label<N: Into<String>, V: Into<String>>(self, name: N, value: V) -> Self;
pub fn Opts::const_label<N: Into<String>, V: Into<String>>(self, name: N, value: V) -> Self;
```

This would be a mostly backwards compatible change with the only implications pertaining to inference.

**Comment by mxinden** [comment]
As far as I can tell this was done in https://github.com/tikv/rust-prometheus/pull/324 by @NikVolf thus closing here.
