### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by benesch** [tikv/rust-prometheus#301]
Thanks for the library! Would it be possible to get a new release soon? In particular it would be nice to get #275 in a version on crates.io so that macro imports work properly in Rust 2018.

**Comment by benesch** [comment]
Hey @breeswish, can you perhaps provide some context on why you marked this as "wontfix"? Happy to move this discussion out of GitHub issues, but I didn't see a mailing list or Gitter chat that would be more suitable.

**Comment by stefan-at-dfinity** [comment]
Yes, a new release would also by appreciated for `Histogram` et al. now export functions such as `get_sample_sum(&self) -> f64` which is useful for testing.

**Comment by benesch** [comment]
Bumping this again. It's been two months. Is this project abandoned?

**Comment by breeswish** [comment]
Sorry for the delay :(  I missed this issue. New version has been released now.
