### ISSUE TITLE
Use rust-audit-check over Deps.rs

### ISSUE THREAD

**Issue by Kixiron** [tikv/rust-prometheus#319]
Deps.rs is unmaintained and not online, [rust-audit-check](https://github.com/marketplace/actions/rust-audit-check) as a workflow feature would be a much better way to detect bad dependencies

**Comment by mxinden** [comment]
Either that or something like https://dependabot.com/. @lucab do I remember correctly that you had experience with the latter?

**Comment by lucab** [comment]
They do perform different tasks, but yes, I like it.
Dependabot takes care of watching dependencies and sending PR whenever new versions are available. It also highlight security advisories. We use it extensively across @coreos repositories, and I'm super happy with it.
However, it currently needs *write* access to a repository, thus the app must be set up by a repo owner (they are working to relax this requirement).

**Comment by mxinden** [comment]
I would be in favor of:

1. Running rust-audit-check on a [scheduled audit](https://github.com/marketplace/actions/rust-audit-check#scheduled-audit).

2. Run dependabot.

In case there are no objections I can look into setting up (1). @breeswish would you mind setting up (2) as you are an owner of the repository?

**Comment by breeswish** [comment]
Unfortunately installing an App requires admin permission to the org, which I don't have. Maybe we can add a `.dependabot` file as described in https://dependabot.com/docs/config-file/ ? @mxinden

**Comment by mxinden** [comment]
@breeswish as far as I can tell just adding the `.dependabot` file is not enough:

> If you haven't done so already, you'll first need to sign up and grant Dependabot access to your repositories.

https://dependabot.com/docs/config-file/

I as well can only request access for dependabot for the `tikv/rust-prometheus` repository, but not grant it directly.

**Comment by lucab** [comment]
I just got notifications on other projects (eg. https://github.com/coreos/afterburn/pull/428) that Dependabot now is part of the "Dependency graph" tab on each repository.
As such, it may be now possible to enable it only on this repository, without organization-wide access. I think it still needs a repo-admin to enable it, though.

**Comment by lucab** [comment]
@mxinden I see dependabot updates are coming in, I think this can closed, right?

**Comment by mxinden** [comment]
Right, missed this. Thanks @lucab.
