### ISSUE TITLE
Implement reset or clear on Registries

### ISSUE THREAD

**Issue by svenstaro** [tikv/rust-prometheus#336]
**Is your feature request related to a problem? Please describe.**
I dynamically create Metrics with a bunch of labels that are mostly the same but might change every now and then. My idea was to simply create a new Registry every scrape and then recreate all Metrics for that Registry. That works but is kind of inconvenient as you can't use any of the nice methods that use the global default Registry.

**Describe the solution you'd like**
It would be sweet if we could clear our all registered Metrics from a pre-existing Registry. This way, I could use the global convenience methods together with the global Registry and then just call `.clear()` on every scrape and re-register my `Metrics` with their new labels.

**Describe alternatives you've considered**
I currently just create a new Registry every loop. This works but is a bit inconvenient.

**Additional context**
There already exists `Register::unregister()` and `MetricVec::reset()` so having more of those "get rid of everything" operations in the same vein would make sense.

**Comment by mxinden** [comment]
Hi @svenstaro,

Thank you for the detailed feature request!

I would like to make sure that the API of the Rust client library (1) is difficult to misuse when used in a common scenario and (2) can support edge cases like your one described.

In my eyes adding a `.clear` method to the global registry opens another way of misusing the library for beginners. At the same time, as you described above, your edge case is already supported via a custom registry (correct me if I am wrong).

Lastly I would like to advocate using a custom registry in the first place, as it prevents all issues connected to the general problem of global state.

That said I am against this change.

What do others think?

**Comment by svenstaro** [comment]
I see your reasoning but I'm not sure I agree to the thesis that it makes misuse easier. After all, you can currently also `unregister()` Metrics and `clear()` would be essentially unregistering all Metrics. My logic is: Is it misuse to unregister all Metrics but not a single Metric?

**Comment by svenstaro** [comment]
Let's just leave it at that and I'll continue using custom registries.
