### ISSUE TITLE
Mention use of "features" flag to use push_metrics function

### ISSUE THREAD

**Issue by thatdevsherry** [tikv/rust-prometheus#345]
As mentioned in #189, we need to pass `features = ["push"]` when adding rust-prometheus as a dependency. It will be better if it's mentioned in the README so people don't have to go through issues to find this.

**Comment by thatdevsherry** [comment]
I think I'm super dumb. I misread the Features section which does specifically this. Can we mention `features = []` to indicate that this is what the features section is talking about?

**Comment by mxinden** [comment]
@thatdevsherry indeed the term features is a bit misleading as it can both imply Cargo `features` as well as general library features. Do you want to propose a pull request that would make this distinction more obvious?

**Comment by thatdevsherry** [comment]
@mxinden sure 👍🏼
