### ISSUE TITLE
Integer Counter type uses signed type (AtomicI64), when unsigned might be preferrable?

### ISSUE THREAD

**Issue by tim-seoss** [tikv/rust-prometheus#364]
`src/counter.rs` defines:

```rust
pub type IntCounter = GenericCounter<AtomicI64>;
```
Looking at the Prometheus spec:

"A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart. For example, you can use a counter to represent the number of requests served, tasks completed, or errors."

I was wondering why `AtomicU64` hadn't been used instead, since according to the spec, negative values are invalid.

With the code as it is, a counter can overflow and wrap to a negative number:

```
# HELP overflow test integer counter
# TYPE overflowable counter
overflowable -6446744073709552000
```

... I think that Prometheus will gracefully handle a reset to zero (e.g. a wrapped AtomicU64), it won't gracefully handle a wrapped signed integer I think (`rate()` won't expect this) I think?  https://www.robustperception.io/how-does-a-prometheus-counter-work

**Comment by breeswish** [comment]
Thanks for pointing it out! Indeed unsigned should be better.
