### ISSUE TITLE
could not find `export` in `syn`

### ISSUE THREAD

**Issue by fggarcia** [tikv/rust-prometheus#378]
**Describe the bug**

Since last syn update

Updating syn v1.0.57 -> v1.0.58

try to build my project

```
error[E0432]: unresolved import `syn::export`
 --> /home/fede/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-static-metric-0.5.0/src/auto_flush_from.rs:4:10
  |
4 | use syn::export::TokenStream2;
  |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `prometheus-static-metric`

```

**Comment by mxinden** [comment]
As far as I can tell the corresponding change in `syn` is https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7. If I understand correctly from the [examples](https://docs.rs/syn/1.0.55/syn/index.html#example-of-a-derive-macro) one should import `TokenStream` via `proc-macro` directly.

@fggarcia would you be interested in proposing a patch?

**Comment by fggarcia** [comment]
Hi @mxinden, i create a PR #380, can you check it?

**Comment by mxinden** [comment]
@fggarcia new release of `prometheus-static-metric` is [tagged](https://github.com/tikv/rust-prometheus/tree/prometheus-static-metric-v0.5.1) and [published](https://crates.io/crates/prometheus-static-metric/0.5.1). Hope this unblocks everything on your side.
