### ISSUE TITLE
New release with reqwest 0.11

### ISSUE THREAD

**Issue by adamchalmers** [tikv/rust-prometheus#394]
Hi! I see that the master branch of this crate is using reqwest 0.11, but it hasn't been released yet. Could you please consider cutting a new patch release so that I can pull in reqwest 0.11? Currently my Rust project is pulling in reqwest 0.10 and 0.11, from Prometheus and from another crate. Obviously I'd rather not include compile two copies of reqwest every time I run my tests :)

Thank you!

**Comment by nrc** [comment]
+1 note that because reqwest uses tokio, we end up pulling in net2 which is unmaintained and thus triggers a vulnerability warning from cargo audit.

**Comment by lucab** [comment]
Tagged: https://github.com/tikv/rust-prometheus/releases/tag/v0.12.0
Published: https://crates.io/crates/prometheus/0.12.0

**Comment by nrc** [comment]
Thank you!
