### ISSUE TITLE
http scrape example

### ISSUE THREAD

**Issue by LukeMauldin** [tikv/rust-prometheus#407]
**Is your feature request related to a problem? Please describe.**
I am familiar with the Go prometheus library and it has multiple examples of implementing metrics with the Go library and exposing them to be scraped by Prometheus (see example below). I would like to have a similar example I can follow in Rust.  I know that Rust, unlike Go, does not have an http server built into the standard library so this may be more difficult to demonstrate.

```go
package main

import (
        "net/http"
        "time"

        "github.com/prometheus/client_golang/prometheus"
        "github.com/prometheus/client_golang/prometheus/promauto"
        "github.com/prometheus/client_golang/prometheus/promhttp"
)

func recordMetrics() {
        go func() {
                for {
                        opsProcessed.Inc()
                        time.Sleep(2 * time.Second)
                }
        }()
}

var (
        opsProcessed = promauto.NewCounter(prometheus.CounterOpts{
                Name: "myapp_processed_ops_total",
                Help: "The total number of processed events",
        })
)

func main() {
        recordMetrics()

        http.Handle("/metrics", promhttp.Handler())
        http.ListenAndServe(":2112", nil)
}
```

**Comment by lucab** [comment]
Are you looking for something like https://github.com/tikv/rust-prometheus/blob/v0.12.0/examples/example_hyper.rs maybe?

**Comment by LukeMauldin** [comment]
Yes, thank you, please close the issue.
