### ISSUE TITLE
Example for operations per second?

### ISSUE THREAD

**Issue by vbmade2000** [tikv/rust-prometheus#409]
Any idea on how to have a metric for the number of operations per second? Like a number of requests/second. I am using the rust-prometheus along with actix_web_prom to use it with Actix.

**Comment by breeswish** [comment]
Hi, you can just increase the counter every time you process an operation. Then Operations/Sec can be calculated by the Prometheus's `rate()` function. See https://prometheus.io/docs/prometheus/latest/querying/functions/#rate

**Comment by vbmade2000** [comment]
Okay. `rate()` function can be used in PromQL. Correct?

**Comment by breeswish** [comment]
Prometheus saves the timestamp during each scrape.

**Comment by lucab** [comment]
Tentatively closing this, as there doesn't seem to be a real bug here.
