### ISSUE TITLE
`procfs 0.9.x` cause panic on linux which version number greater than 255

### ISSUE THREAD

**Issue by DCjanus** [tikv/rust-prometheus#414]
`procfs 0.9.x` assume numbers in Linux kernel version is small than 256, and parse text from '/proc/sys/kernel/osrelease' to [three `u8`](https://docs.rs/procfs/0.9.1/procfs/sys/kernel/struct.Version.html)

And since Linux has been release [a version which patch version is 256](https://lwn.net/Articles/845206/), [this line in procfs 0.9.x](https://github.com/eminence/procfs/blob/86d71e5235a36fb0718028d58662863d88a1f158/src/lib.rs#L303) would panic.

In the last release of this lib(`0.12.0`), we are still using the `procfs 0.9.x`, which would cause panic, if my Linux version number greater than 255.

ref: https://github.com/eminence/procfs/pull/137
ref: https://github.com/tikv/rust-prometheus/pull/408

**Comment by DCjanus** [comment]
This change is import to some people, please release a new version.

**Comment by lucab** [comment]
Release PR at https://github.com/tikv/rust-prometheus/issues/414.
