### ISSUE TITLE
Support Prometheus HTTP API

### ISSUE THREAD

**Issue by iosmanthus** [tikv/rust-prometheus#419]
**Is your feature request related to a problem? Please describe.**

This library only provides pushing/pulling metrics features, without the proper manner to interact with Prometheus like API provided in [client_golang](https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/api.go#L222). Programs could use these APIs to implement features like telemetry.

**Describe the solution you'd like**
Port the API logic from [client_golang](https://github.com/prometheus/client_golang), we might implement only query API first, then add another API incrementally.

**Comment by lucab** [comment]
Thanks for the report.
However I'd say that the scope of this library is mostly around instrumenting Rust applications.
A client library for the Prometheus service would be nice to have (I'm not aware of any right now), but I feel that it would be out of scope for most of the current consumers. I'd rather not impose that burden to everyone by stuffing more things into the existing crate.

Thus, I'd say that such client would better live as its own crate. We may consider having its source as a sub-workspace here, but honestly to me it would feel simpler/cleaner as a fully separate project.

**Comment by lucab** [comment]
In the meanwhile I've seen a few new crates being developed to tackle this:
 * `prometheus-http-api` - https://github.com/sebosp/prometheus-http-api-rs
 * `prometheus-http-query` - https://github.com/puetzp/prometheus-http-query

I haven't used any of those, but I think future development should be oriented towards those. I'm thus closing this ticket.
