### ISSUE TITLE
Support time stamps when exporting metrics

### ISSUE THREAD

**Issue by Mikadore** [tikv/rust-prometheus#423]
**Is your feature request related to a problem? Please describe.**
In order to backfill metrics into prometheus, time stamps are needed. Currently, this crate doesn't provide a way to add time stamps when exporting using either `ProtobufEncoder` or `TextEncoder`

**Describe the solution you'd like**
Add a method to `ProtobufEncoder` and `TextEncoder`, perhaps something like `encode_with_timestamp`. 

**Describe alternatives you've considered**
Hacking around manually with exported metrics. This is error prone, but also a feature that falls within the use case of this crate.

**Comment by Mikadore** [comment]
This can be done using:
```rust
        metric_families
            .into_iter()
            .map(|mut fam| {
                for metric in fam.mut_metric() {
                    metric.set_timestamp_ms(timestamp)
                }
                fam
            })
            .collect()
```

**Comment by lucab** [comment]
Welcome and thanks for the report. Are you maybe chasing the same feature request as https://github.com/tikv/rust-prometheus/issues/382?

**Comment by Mikadore** [comment]
> Welcome and thanks for the report. Are you maybe chasing the same feature request as #382?

Hello, yes, it seems I didn't search carefully enough. Thanks :D
