### ISSUE TITLE
Why value module is private?

### ISSUE THREAD

**Issue by rajaSahil** [tikv/rust-prometheus#435]
While implementing a new collector, I am not able to initialize Value. Is there any reason to make it a private module?

**Comment by breeswish** [comment]
@rajaSahil Hi, currently the publicly exposed interfaces are standard metric types like Counter, Histogram and Gauge. Could you illustrate what kind of Value type do you need when implementing a collector?

**Comment by rajaSahil** [comment]
Was trying to write a custom collector and have figured it out.
Closing this issue as it is not required.
